import type { StructureDefinition } from "./generate.ts";

/**
 * A reviewable account of what changes between two IG targets, at the level
 * a composer author cares about: which profiles appear or disappear, and for
 * each shared profile, which elements change cardinality, type, fixed value
 * or binding. Written to markdown so an IG upgrade is a diff someone reads.
 */
export function diffTargets(
  fromLabel: string,
  from: readonly StructureDefinition[],
  toLabel: string,
  to: readonly StructureDefinition[],
): string {
  const profiles = (sds: readonly StructureDefinition[]) =>
    new Map(sds.filter((s) => s.derivation === "constraint").map((s) => [s.url, s]));
  const a = profiles(from);
  const b = profiles(to);
  const name = (url: string) => (a.get(url) ?? b.get(url))?.name ?? url;
  const added = [...b.keys()].filter((u) => !a.has(u)).sort();
  const removed = [...a.keys()].filter((u) => !b.has(u)).sort();

  const out: string[] = [
    `# ${fromLabel} to ${toLabel}`,
    "",
    "Generated by `pnpm regen`. Do not edit.",
    "",
    `- Profiles and extensions in ${fromLabel}: ${a.size}`,
    `- Profiles and extensions in ${toLabel}: ${b.size}`,
    `- Added: ${added.length}, removed: ${removed.length}`,
    "",
  ];

  if (removed.length > 0) {
    out.push("## Removed", "");
    for (const u of removed) out.push(`- \`${name(u)}\` — ${u}`);
    out.push("");
  }
  if (added.length > 0) {
    out.push("## Added", "");
    for (const u of added) out.push(`- \`${name(u)}\` (${b.get(u)?.type}) — ${u}`);
    out.push("");
  }

  out.push("## Changed", "");
  let changedAny = false;
  for (const url of [...a.keys()].filter((u) => b.has(u)).sort()) {
    const rows = compare(a.get(url) as StructureDefinition, b.get(url) as StructureDefinition);
    if (rows.length === 0) continue;
    changedAny = true;
    out.push(`### ${name(url)}`, "", "| Element | Change |", "| --- | --- |");
    for (const [id, change] of rows) out.push(`| \`${id}\` | ${change.replaceAll("|", "\\|")} |`);
    out.push("");
  }
  if (!changedAny) out.push("No shared profile changes.", "");
  return out.join("\n");
}

type Element = NonNullable<StructureDefinition["snapshot"]>["element"][number];

function summary(e: Element): Record<string, string> {
  const fixed = Object.keys(e)
    .filter((k) => /^(fixed|pattern)[A-Z]/.test(k))
    .map((k) => `${k}=${JSON.stringify(e[k])}`)
    .join(" ");
  return {
    cardinality: `${e.min ?? 0}..${e.max ?? "*"}`,
    type: (e.type ?? [])
      .map((t) => t.code + (t.profile ? `<${t.profile.join(",")}>` : ""))
      .join(" \\| "),
    fixed,
    binding: e.binding ? `${e.binding.strength} ${e.binding.valueSet ?? ""}`.trim() : "",
  };
}

function compare(a: StructureDefinition, b: StructureDefinition): [string, string][] {
  const ea = new Map((a.snapshot?.element ?? []).map((e) => [e.id, e]));
  const eb = new Map((b.snapshot?.element ?? []).map((e) => [e.id, e]));
  const rows: [string, string][] = [];
  for (const id of [...new Set([...ea.keys(), ...eb.keys()])].sort()) {
    const x = ea.get(id);
    const y = eb.get(id);
    if (!x && y) {
      const s = summary(y);
      rows.push([id, `added, ${s.cardinality}${s.type ? ` ${s.type}` : ""}`]);
    } else if (x && !y) {
      rows.push([id, "removed"]);
    } else if (x && y) {
      const sx = summary(x);
      const sy = summary(y);
      const changes = Object.keys(sx)
        .filter((k) => sx[k] !== sy[k])
        .map((k) => `${k}: \`${sx[k] || "none"}\` → \`${sy[k] || "none"}\``);
      if (changes.length > 0) rows.push([id, changes.join("; ")]);
    }
  }
  return rows;
}
