/**
 * `pnpm regen`: rebuild `src/generated` from the pinned FHIR packages.
 *
 *   pnpm regen                        every target, plus the diff between them
 *   pnpm regen --target ndhm-6.5.0    one target (what CI checks on every push)
 *
 * The output is checked in. Running this twice must produce no diff; CI holds
 * it to that. After writing a target, regen parses every example the IG ships
 * against the generated schemas and fails if any is rejected, so a generator
 * bug that turns away valid resources cannot reach a commit.
 */
import { mkdir, rm, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { parseArgs } from "node:util";
import { HI_TYPES, IG_PACKAGE } from "../../core/src/index.ts";
import { diffTargets } from "./diff.ts";
import { loadPackage } from "./fetch.ts";
import {
  emitPrimitives,
  ModuleEmitter,
  type StructureDefinition,
  structureDefinitions,
  Universe,
} from "./generate.ts";
import { HI_TYPE_PROFILES, NOT_HI_TYPES } from "./hi-types.ts";
import { CORE, TARGETS, type Target } from "./sources.ts";

const pkgDir = join(dirname(fileURLToPath(import.meta.url)), "..");
const outDir = join(pkgDir, "src", "generated");
const cacheDir = join(pkgDir, ".cache");

const { values } = parseArgs({ options: { target: { type: "string", multiple: true } } });
const selected = values.target ? TARGETS.filter((t) => values.target?.includes(t.slug)) : TARGETS;
if (values.target && selected.length !== values.target.length) {
  throw new Error(`unknown target; expected one of ${TARGETS.map((t) => t.slug).join(", ")}`);
}

const release = TARGETS.find((t) => t.status === "release");
if (release?.version !== IG_PACKAGE.version) {
  throw new Error(
    `@nuskha/core pins ${IG_PACKAGE.id}#${IG_PACKAGE.version} but the release target is ${release?.version}`,
  );
}

const header = (from: string) =>
  `// Generated by packages/ig/scripts/regen.ts from ${from}.\n// Do not edit. Run \`pnpm regen\` instead.\n\n`;

async function write(path: string, text: string): Promise<void> {
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, text.endsWith("\n") ? text : `${text}\n`);
}

const core = structureDefinitions(await loadPackage(CORE, cacheDir));
const coreLabel = `${CORE.id}#${CORE.version} (sha256 ${CORE.sha256})`;

// ---- Datatypes, shared by every target ------------------------------------

{
  const u = new Universe(core);
  const m = new ModuleEmitter(u, "");
  m.raw(
    `${header(coreLabel)}import { z } from "zod";\nimport * as rt from "../../runtime.ts";\n\n` +
      "// Referenced by generated fixed and pattern checks.\nvoid rt;\n",
  );
  m.raw(emitPrimitives(u));
  m.raw(
    "/** Any resource, where a profile allows one without saying which. */\n" +
      "export interface AnyResource {\n  resourceType: string;\n  [key: string]: unknown;\n}\n" +
      "export const AnyResource: z.ZodType<AnyResource> = z.looseObject({ resourceType: z.string() });\n",
  );
  const unchecked: string[] = [];
  for (const [name, sd] of [...u.datatypes].sort(([a], [b]) => a.localeCompare(b))) {
    const items = m.emitRoot(name, sd);
    unchecked.push(`  ${name}: ${JSON.stringify(items)},`);
  }
  for (const w of m.wanted) {
    if (!m.has(w)) throw new Error(`datatype ${w} is referenced but was not emitted`);
  }
  m.raw(
    "/** Constraints on each datatype the schemas above do not evaluate. */\n" +
      `export const UNCHECKED = {\n${unchecked.join("\n")}\n} as const;\n`,
  );
  await write(join(outDir, "r4", "datatypes.ts"), m.source);
}

// ---- One module set per IG target -----------------------------------------

const loaded = new Map<string, StructureDefinition[]>();

for (const target of selected) {
  const files = await loadPackage(target, cacheDir);
  const ig = structureDefinitions(files);
  loaded.set(target.slug, ig);
  const u = new Universe(core);
  u.addPackage(ig);
  const label = `${target.id}#${target.version}${target.status === "preview" ? " preview" : ""} (sha256 ${target.sha256})`;

  const profiles = ig.filter((s) => s.kind === "resource" && s.derivation === "constraint");
  checkHiTypes(target, profiles);

  const m = new ModuleEmitter(u, "dt.");
  m.raw(
    `${header(label)}import { z } from "zod";\nimport * as rt from "../../runtime.ts";\nimport * as dt from "../r4/datatypes.ts";\n\n` +
      "// Referenced by generated slice and choice checks.\nvoid rt;\n",
  );
  const registry: string[] = [];
  for (const sd of [...profiles].sort((a, b) => a.name.localeCompare(b.name))) {
    const unchecked = m.emitRoot(sd.name, sd, sd.type);
    registry.push(
      `  ${sd.name}: {\n    url: ${JSON.stringify(sd.url)},\n    type: ${JSON.stringify(sd.type)},\n` +
        `    title: ${JSON.stringify(sd.title ?? sd.name)},\n    schema: p.${sd.name},\n` +
        `    unchecked: ${JSON.stringify(unchecked)},\n  },`,
    );
  }

  const dir = join(outDir, target.slug);
  await rm(dir, { recursive: true, force: true });
  await write(join(dir, "profiles.ts"), m.source);
  await write(
    join(dir, "registry.ts"),
    `${header(label)}import type { HiType } from "@nuskha/core";\nimport type { ProfileEntry } from "../../registry-types.ts";\nimport * as p from "./profiles.ts";\n\n` +
      `export const PACKAGE = ${JSON.stringify(
        { id: target.id, version: target.version, status: target.status, sha256: target.sha256 },
        null,
        2,
      )} as const;\n\n` +
      `/** Every resource profile in the IG, by name. */\nexport const PROFILES = {\n${registry.join("\n")}\n} as const satisfies Record<string, ProfileEntry>;\n\n` +
      "export type ProfileName = keyof typeof PROFILES;\n\n" +
      "/** Profiles keyed by canonical URL, for resolving `meta.profile`. */\n" +
      "export const PROFILES_BY_URL: ReadonlyMap<string, ProfileEntry> = new Map(\n" +
      "  Object.values(PROFILES).map((entry) => [entry.url, entry]),\n);\n\n" +
      "/** The Composition profile each health information type is built on. */\n" +
      `export const HI_TYPE_PROFILES = ${JSON.stringify(HI_TYPE_PROFILES, null, 2)} as const satisfies Record<HiType, ProfileName>;\n`,
  );
  await write(
    join(dir, "index.ts"),
    `${header(label)}export * from "./profiles.ts";\nexport * from "./registry.ts";\n`,
  );

  await selfCheck(target, files, pathToFileURL(join(dir, "registry.ts")).href);
}

// ---- The upgrade diff ------------------------------------------------------

if (selected.length === TARGETS.length) {
  const [a, b] = TARGETS as [Target, Target];
  const label = (t: Target) => `${t.id}#${t.version}${t.status === "preview" ? "-preview" : ""}`;
  await write(
    join(outDir, `diff-${a.slug}-to-${b.slug}.md`),
    diffTargets(label(a), loaded.get(a.slug) ?? [], label(b), loaded.get(b.slug) ?? []),
  );
}

// ---------------------------------------------------------------------------

function checkHiTypes(target: Target, profiles: readonly StructureDefinition[]): void {
  const byName = new Map(profiles.map((p) => [p.name, p]));
  const errors: string[] = [];
  for (const hi of HI_TYPES) {
    const p = byName.get(HI_TYPE_PROFILES[hi]);
    if (!p)
      errors.push(`${hi} maps to ${HI_TYPE_PROFILES[hi]}, which ${target.slug} does not define`);
    else if (p.type !== "Composition") errors.push(`${hi} maps to ${p.name}, a ${p.type}`);
  }
  const mapped = new Set(Object.values(HI_TYPE_PROFILES));
  for (const p of profiles) {
    if (p.type === "Composition" && !mapped.has(p.name) && !(p.name in NOT_HI_TYPES)) {
      errors.push(`${target.slug} defines Composition profile ${p.name}, which no hiType maps to`);
    }
  }
  if (errors.length > 0) throw new Error(`hiType mapping is wrong:\n  ${errors.join("\n  ")}`);
}

interface Parseable {
  readonly schema: { safeParse(v: unknown): { success: boolean; error?: { issues: unknown[] } } };
}

async function selfCheck(target: Target, files: Map<string, unknown>, registry: string) {
  const { PROFILES_BY_URL } = (await import(registry)) as {
    PROFILES_BY_URL: ReadonlyMap<string, Parseable>;
  };
  const failures: string[] = [];
  let checked = 0;

  const visit = (resource: unknown, where: string) => {
    if (resource === null || typeof resource !== "object") return;
    const r = resource as {
      meta?: { profile?: string[] };
      entry?: { resource?: unknown }[];
      contained?: unknown[];
    };
    for (const url of r.meta?.profile ?? []) {
      const entry = PROFILES_BY_URL.get(url.split("|")[0] as string);
      if (!entry) continue;
      checked++;
      const result = entry.schema.safeParse(resource);
      if (!result.success) {
        failures.push(`${where} against ${url}:\n    ${JSON.stringify(result.error?.issues)}`);
      }
    }
    r.entry?.forEach((e, i) => {
      visit(e.resource, `${where} entry[${i}]`);
    });
    r.contained?.forEach((c, i) => {
      visit(c, `${where} contained[${i}]`);
    });
  };

  for (const [name, json] of [...files].sort(([a], [b]) => a.localeCompare(b))) {
    if (name.startsWith("package/example/")) visit(json, name.slice("package/example/".length));
  }

  process.stderr.write(
    `${target.slug}: ${checked} example resources checked, ${failures.length} rejected\n`,
  );
  if (failures.length > 0) {
    throw new Error(
      `generated schemas reject examples the IG itself ships:\n  ${failures.join("\n  ")}`,
    );
  }
}
